### ISSUE TITLE
Geo target list does not contain all targets

### ISSUE THREAD

**Issue by raalderink** [MicrosoftDocs/Advertising-docs#568]
When downloading a GeographicPerformanceReport, it will contain geo targets that are not available in the list of geo targets provided through the API, although this is not stated anywhere in the docs.

For example, our report contains the State `La Paz` with location ID 645. This location is not available in that list of targets. This makes it impossible to map them to the actual targets in our database.

Please clarify if them missing is intended, and if so, how we would go forward in properly mapping these targets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a20ceb04-fa33-bfb4-60f2-00093a8c3cc9
* Version Independent ID: bf87d489-1bf2-a70e-c7d1-9b98aa02b6b1
* Content: [GeographicPerformanceReportColumn Value Set - Reporting - Bing Ads](https://docs.microsoft.com/en-us/bingads/reporting-service/geographicperformancereportcolumn?view=bingads-13#feedback)
* Content Source: [BingAds/bingads-13/reporting-service/geographicperformancereportcolumn.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/master/BingAds/bingads-13/reporting-service/geographicperformancereportcolumn.md)
* Service: **bing-ads-reporting-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@raalderink I confirmed this is currently by design, and we do not support a performance report that always map location IDs directly to the targeted locations. We'll update the documentation to clarify. The team is investigating whether/when to prioritize the request, so now is a great time to add your vote [here](https://microsoftadvertising.uservoice.com/forums/82363-microsoft-advertising-feature-suggestions/suggestions/5951905-targeted-location-reports). Thank you.
