### ISSUE TITLE
Report only returns download url no option to request only xml/csv

### ISSUE THREAD

**Issue by WouterVeen** [MicrosoftDocs/Advertising-docs#657]
For the Report creation function you only can get a download url, instead it would be better if you can get back a direct object formatted witch given format. Like a param ReturnType => csv/xml/json/tsv and with a extra param ReturnLink = true it will return a download link to a zip file. PS the json formatted return would be a awsome feature to have in PHP.

**Comment by eric-urban** [comment]
@WouterVeen at the service level for performance and flexibility this is by design. Note, the .NET, Java, and Python SDKs abstract this detail and allow you to [access the report data directly](https://docs.microsoft.com/en-us/advertising/guides/sdk-reporting-service-manager?view=bingads-13#reportcontainer) (although in the background a report download URL is used). If you would like to see a similar feature via the PHP library please feel free to submit a request [here](https://github.com/BingAds/BingAds-PHP-SDK/issues). Thanks!
